/**
 * Section Icons
 *
 * Icon mapping for config sections. Used in sidebar navigation.
 */

import {
  Globe,
  Bot,
  Radio,
  Wrench,
  Terminal,
  Users,
  Clock,
  Sparkles,
  Puzzle,
  FileText,
  Lock,
  Box,
  Wand2,
  Download,
  Activity,
  Server,
  Volume2,
  MessageSquare,
  Link,
  Layout,
  Monitor,
  Webhook,
  Shield,
  Bell,
  Image,
  Cpu,
  HardDrive,
  Network,
  Key,
  Layers,
  Zap,
  Circle,
  RefreshCw,
  Settings2,
} from "lucide-preact";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const SECTION_ICONS: Record<string, any> = {
  // Core
  gateway: Globe,
  agents: Bot,
  channels: Radio,
  tools: Wrench,
  commands: Terminal,
  session: Users,
  cron: Clock,
  skills: Sparkles,
  plugins: Puzzle,
  logging: FileText,
  auth: Lock,
  models: Box,
  wizard: Wand2,
  update: Download,
  diagnostics: Activity,
  nodeHost: Server,
  // Additional sections
  audio: Volume2,
  messages: MessageSquare,
  bindings: Link,
  ui: Layout,
  browser: Monitor,
  hooks: Webhook,
  web: Globe,
  canvas: Image,
  canvasHost: Image,
  approvals: Shield,
  notifications: Bell,
  meta: FileText,
  env: HardDrive,
  nodes: Server,
  broadcast: Radio,
  media: Image,
  network: Network,
  secrets: Key,
  memory: Cpu,
  memorySearch: Cpu,
  storage: HardDrive,
  tls: Lock,
  remote: Network,
  reload: RefreshCw,
  tailscale: Network,
  sandbox: Box,
  context: Layers,
  contextPruning: Layers,
  compaction: Zap,
  heartbeat: Activity,
  defaults: Settings2,
};

/** Default icon for unknown sections */
export const DEFAULT_SECTION_ICON = Circle;
